enum LOG_LEVEL {
    DEBUG,
    INFO
}

class Constants {
    INDUSTRY_COAL_MINE = 0;
    INDUSTRY_POWER_STATION = 1;
    CARGO_COAL = 1;
    LOG_LEVEL = LOG_LEVEL.DEBUG;

    LOW_QUEUE_PRIORITY = 10;
    DEFAULT_QUEUE_PRIORITY = 5;
    HIGH_QUEUE_PRIORITY = 3;
}
